development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: hardikbalar102@gmail.com
  :password: balar123
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: hardikbalar102@gmail.com
  :password: balar123
  :enable_starttls_auto: true