
# Name of the installation
name: "WADT 2014"
conf_name: "WADT"
conf_year: "2014"

#Banner Details 
fullname: "22nd International Workshop on Algebraic Development Techniques"
place: "Sinaia, Romania,September 4-7,2014"

# Hostname of the installation
hostname: wadt2014.cs.ovgu.de
test_hostname: test.wadt2014.cs.ovgu.de

# Optional asset host for delivery of static files (css, images, javascripts)
# asset_host: assets.example.com

# Sender address for outgoing mail
email: wadt2014.confirmation@gmail.com

contact: hardikbalar101@gmail.com

#email address for admin to log in as admin
admin_email: addminwadt2014@gmail.com
password: password

# Footer links and texts
footer:
  - text: WADT 2014
    href: "admin_email"
  - text: Email
    href: "hostname"

development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: wadt2014.confirmation
  :password: wadt1234
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: wadt2014.confirmation
  :password: wadt1234
  :enable_starttls_auto: true

st_hash:
 5: 
  - Register
  - Format & Location
  - Committees
  - Important Dates
  - Travel
  - Accommodation
  - Sponsors & Grants
  - Contact
  - Speakers
  - Accepted Abstracts
 6:  
  - Register
  - Format & Location
  - Committees
  - Important Dates
  - Travel
  - Accommodation
  - Sponsors & Grants
  - Contact
  - Speakers
  - Accepted Abstracts
  - Program
 1:
  - Format & Location 
  - Register
  - Committees
  - Important Dates
  - Submission
  - Travel
  - Accommodation
  - Sponsors & Grants
  - Contact
 7: 
  - Format & Location
  - Committees
  - Important Dates
  - Travel
  - Accommodation
  - Sponsors & Grants
  - Contact
  - Speakers
  - Accepted Abstracts
  - Program
 2: 
  - Format & Location
  - Committees
  - Important Dates
  - Travel
  - Accommodation
  - Sponsors & Grants
  - Contact
  - Speakers
 8: 
  - Format & Location
  - Committees
  - Important Dates
  - Travel
  - Accommodation
  - Sponsors & Grants
  - Contact
  - Speakers
  - Accepted Abstracts
  - Program
  - Submission
  - Finalized Reviews 
  - Accepted Papers
 3: 
  - Format & Location
  - Register
  - Committees
  - Important Dates
  - Speakers
  - Travel
  - Accommodation
  - Sponsors & Grants
  - Submission
  - Contact
 9: 
  - Format & Location
  - Committees
  - Important Dates
  - Travel
  - Accommodation
  - Sponsors & Grants
  - Contact
  - Speakers
  - Accepted Abstracts
  - Program
  - Submission
  - Finalized Reviews
  - Accepted Papers
  - Proceedings
 4: 
  - Format & Location
  - Register
  - Committees
  - Important Dates
  - Travel
  - Accommodation
  - Sponsors & Grants
  - Contact
  - Speakers
  - Submission


